// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/demo.proto

package demo

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{0}
}
func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{1}
}
func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

func (m *HelloResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DemoReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoReq) Reset()         { *m = DemoReq{} }
func (m *DemoReq) String() string { return proto.CompactTextString(m) }
func (*DemoReq) ProtoMessage()    {}
func (*DemoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{2}
}
func (m *DemoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoReq.Unmarshal(m, b)
}
func (m *DemoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoReq.Marshal(b, m, deterministic)
}
func (m *DemoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoReq.Merge(m, src)
}
func (m *DemoReq) XXX_Size() int {
	return xxx_messageInfo_DemoReq.Size(m)
}
func (m *DemoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DemoReq proto.InternalMessageInfo

func (m *DemoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DemoResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoResp) Reset()         { *m = DemoResp{} }
func (m *DemoResp) String() string { return proto.CompactTextString(m) }
func (*DemoResp) ProtoMessage()    {}
func (*DemoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_982f2043e503afee, []int{3}
}
func (m *DemoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoResp.Unmarshal(m, b)
}
func (m *DemoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoResp.Marshal(b, m, deterministic)
}
func (m *DemoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResp.Merge(m, src)
}
func (m *DemoResp) XXX_Size() int {
	return xxx_messageInfo_DemoResp.Size(m)
}
func (m *DemoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResp.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResp proto.InternalMessageInfo

func (m *DemoResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloReq)(nil), "demo.service.v1.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "demo.service.v1.HelloResp")
	proto.RegisterType((*DemoReq)(nil), "demo.service.v1.DemoReq")
	proto.RegisterType((*DemoResp)(nil), "demo.service.v1.DemoResp")
}

func init() { proto.RegisterFile("api/demo.proto", fileDescriptor_982f2043e503afee) }

var fileDescriptor_982f2043e503afee = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0xc7, 0xc9, 0x8f, 0xfe, 0xfa, 0x67, 0x91, 0x0a, 0xab, 0x60, 0x1b, 0x84, 0x96, 0x55, 0x41,
	0x14, 0xb3, 0xa8, 0xa0, 0xd0, 0x63, 0xf5, 0xe0, 0xd5, 0x1c, 0xbd, 0x6d, 0xd3, 0x69, 0xba, 0x90,
	0xec, 0x6c, 0x37, 0xdb, 0x3e, 0x80, 0xaf, 0xe0, 0x73, 0xf8, 0x34, 0xde, 0x7b, 0xf2, 0x09, 0xfa,
	0x04, 0x92, 0x49, 0x7b, 0x50, 0x89, 0xb7, 0xf9, 0xce, 0x7c, 0xbf, 0x9f, 0xc9, 0x64, 0x59, 0x57,
	0x59, 0x2d, 0xa7, 0x90, 0x63, 0x64, 0x1d, 0x7a, 0xe4, 0xfb, 0x54, 0x17, 0xe0, 0x56, 0x3a, 0x81,
	0x68, 0x75, 0x1d, 0x1e, 0xa7, 0x88, 0x69, 0x06, 0xb2, 0xf4, 0x29, 0x63, 0xd0, 0x2b, 0xaf, 0xd1,
	0x14, 0x95, 0x3d, 0xbc, 0x4a, 0xb5, 0x9f, 0x2f, 0x27, 0x51, 0x82, 0xb9, 0x4c, 0x31, 0x45, 0x49,
	0xed, 0xc9, 0x72, 0x46, 0x8a, 0x04, 0x55, 0x95, 0x5d, 0x3c, 0xb0, 0xf6, 0x13, 0x64, 0x19, 0xc6,
	0xb0, 0xe0, 0xf7, 0xac, 0x61, 0x54, 0x0e, 0xbd, 0x60, 0x18, 0x9c, 0x77, 0xc6, 0x27, 0x9b, 0xf5,
	0x60, 0x30, 0x43, 0x97, 0x8f, 0x44, 0xd9, 0x15, 0xc3, 0x95, 0xca, 0xf4, 0x54, 0x79, 0x18, 0x09,
	0x07, 0x8b, 0xa5, 0x76, 0x30, 0x15, 0x31, 0x05, 0xc4, 0x19, 0xeb, 0x6c, 0x21, 0x85, 0xe5, 0x3d,
	0xd6, 0x4a, 0xd0, 0x78, 0x30, 0xbe, 0x02, 0xc5, 0x3b, 0x29, 0xee, 0x58, 0xeb, 0x11, 0x72, 0x5a,
	0x75, 0xf9, 0x6d, 0xd5, 0xd1, 0x66, 0x3d, 0x38, 0xa8, 0xc7, 0x9f, 0xb2, 0x76, 0x95, 0xfb, 0x8b,
	0x7e, 0xf3, 0x1e, 0xb0, 0x46, 0x69, 0xe3, 0x31, 0xfb, 0x4f, 0x5f, 0xc3, 0xfb, 0xd1, 0x8f, 0x5f,
	0x17, 0xed, 0x4e, 0x0d, 0xc3, 0xba, 0x51, 0x61, 0x05, 0x7f, 0xfd, 0xf8, 0x7c, 0xfb, 0xb7, 0xc7,
	0x99, 0x74, 0x36, 0x91, 0x73, 0x42, 0x3d, 0x6f, 0xd9, 0xbd, 0x5f, 0xb9, 0xed, 0x45, 0x61, 0xbf,
	0x66, 0x52, 0x58, 0x71, 0x48, 0xc0, 0xae, 0xe8, 0x10, 0xb0, 0xb4, 0x8d, 0x82, 0x8b, 0x71, 0xf3,
	0xa5, 0x51, 0x96, 0x93, 0x26, 0x3d, 0xc4, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xa3,
	0x85, 0x90, 0xf8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
	Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoResp, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, "/demo.service.v1.Demo/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoResp, error) {
	out := new(DemoResp)
	err := c.cc.Invoke(ctx, "/demo.service.v1.Demo/Demo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	Hello(context.Context, *HelloReq) (*HelloResp, error)
	Demo(context.Context, *DemoReq) (*DemoResp, error)
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) Hello(ctx context.Context, req *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedDemoServer) Demo(ctx context.Context, req *DemoReq) (*DemoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Demo not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.service.v1.Demo/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.service.v1.Demo/Demo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Demo(ctx, req.(*DemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.service.v1.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Demo_Hello_Handler,
		},
		{
			MethodName: "Demo",
			Handler:    _Demo_Demo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/demo.proto",
}
